version: 0.0.{build}

image:
  - Visual Studio 2017
  - Ubuntu

shallow_clone: true

init:
  - ps: if ($env:APPVEYOR_REPO_TAG_NAME) { Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME.Substring(1) }

platform:
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - ps: msbuild -t:restore
  - ps: ./Vsxmd/Test.ps1 -Prepare

test_script:
  - ps: ./Vsxmd/Test.ps1 -Run

artifacts:
  - path: 'Vsxmd\**\*.nupkg'

deploy:
  - release: v$(APPVEYOR_BUILD_VERSION)
    provider: GitHub
    draft: false
    prerelease: false
    auth_token:
      secure: jvNlko7Yh8M98umyLQhc8u/RQsaYWXA2ni9+7ku3V9E6KqjGbmRO+4Veq71m2jmz
    on:
      appveyor_repo_tag: true
