name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: [ '8.0', '9.0' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore --framework net${{ matrix.dotnet-version }}

    - name: Build
      run: dotnet build --framework net${{ matrix.dotnet-version }} --no-restore

    - name: Test
      run: dotnet test --framework net${{ matrix.dotnet-version }} --no-build --verbosity normal
